FROM ruby:3.4.8
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV RAILS_ENV development

RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

RUN apt-get update -qq \
&& apt-get install -y \
   build-essential \
   default-mysql-client \
   default-libmysqlclient-dev \
   libvips \
   nodejs \
   vim \
&& npm install -g yarn@1.22.22 \
&& rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN mkdir /myapp
WORKDIR /myapp

RUN gem install bundler

COPY Gemfile Gemfile.lock ./
RUN bundle config set frozen false && \
    bundle install

COPY . /myapp

EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0"]
